# This is a TOML configuration file.

# if set to true, allow running outside market open hours
# bypass_market_schedule = true

# ticket scanners, may have several
# scanners during the day
[[scanners]]
    [scanners.momentum]
        # check documentation for supported providers
        provider = 'polygon'

        # scan for tickers with minimal volume since day start
        min_volume = 30000

        # minimum daily percentage gap
        min_gap = 3.5

        # minimum last day dollar volume
        min_last_dv = 500000

        min_share_price = 2.0
        max_share_price = 20.0

        # How many minutes from market open, to start running scanner
        from_market_open = 15

        # recurrence = 5

        # max_symbols = 440

# trading strategies, can have several *strategy* blocks
[[strategies]]
    # strategy class name, must implement Strategy class
    [strategies.MomentumLong]
        # filename = "strategies/momentum_long.py"

        # check_patterns = true

        # trading schedules block, trades many have
        # several windows within the same day
        [[strategies.MomentumLong.schedule]]
            start = 15
            duration = 150





