# This is a TOML configuration file.

# if set to true, allow running outside market open hours
bypass_market_schedule = false

# set max portfolio_value
# portfolio_value = 25000.0

# set risk factor per trade
# risk = 0.001

# how many minutes, before end of the trading day to enforce liqudation
# market_liquidation_end_time_minutes = 15

# if set, existing positions won't be pull into a run,
# this configuration is helpful when testing different
# scanners & strategies on different dockers, all sharing
# same paper/production accounts
# skip_existing = true

# if set, only scanners would run, w/o running consumer or producers
# useful for debugging new scanners
# test_scanners = true

events = ["second", "minute", "trade", "quote"]

# ticket scanners, may have several
# scanners during the day
[scanners]
[scanners.momentum]
# check documentation for supported providers
provider = 'polygon'

# scan for tickers with minimal volume since day start
min_volume = 30000

# minimum daily percentage gap
min_gap = 3.5

# minimum last day dollar volume
min_last_dv = 500000

max_share_price = 20.0
min_share_price = 2.0

# How many minutes from market open, to start running scanner
from_market_open = 15

recurrence = 5

# target_strategy_name = ""

# trading strategies, can have several *strategy* blocks
[strategies]
# strategy class name, must implement Strategy class

[strategies.MomentumLongV3]
filename = "./momentum_long_simplified.py"

[[strategies.MomentumLongV3.schedule]]
duration = 60
start = 15
